name: blue_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  agora_rtc_engine: ^6.1.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.18
  flutter_svg: ^2.0.1
  google_fonts: ^4.0.3
  hexcolor: ^3.0.1
  permission_handler: ^10.2.0
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: Images/splash.png
  color: "#927FF2"

flutter:
  assets:
    - Assets/

  uses-material-design: true
